apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-jenkins
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
  labels:
    app.kubernetes.io/part-of: fake-jenkins
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: fake-jenkins
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      app.kubernetes.io/part-of: fake-jenkins
      apps.tanzu.vmware.com/has-tests: "true"
      apps.tanzu.vmware.com/workload-type: server
      carto.run/workload-name: fake-jenkins
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"fake-jenkins","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"server"},"name":"fake-jenkins","namespace":"dev"},"spec":{"params":[{"name":"testing_pipeline_matching_labels","value":{"apps.tanzu.vmware.com/pipeline":"golang"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/carto-run/fake-jenkins"}}}}
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: fake-jenkins
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: server
        carto.run/workload-name: fake-jenkins
    spec:
      containers:
      - image: gcr.io/rawlingsj/fake-jenkins-dev@sha256:b8d7932ace8da502222f35081fbc2e66eee21277e46922fed610a37d3d5b483c
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: fake-jenkins
  labels:
    app.kubernetes.io/part-of: fake-jenkins
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: fake-jenkins
spec:
  selector:
    app.kubernetes.io/component: run
    app.kubernetes.io/part-of: fake-jenkins
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    carto.run/workload-name: fake-jenkins
  ports:
  - targetPort: 8080
    port: 8080
    name: http

