apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
  labels:
    app.kubernetes.io/part-of: tekton
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: worker
    app.kubernetes.io/component: run
    carto.run/workload-name: tekton
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      app.kubernetes.io/part-of: tekton
      apps.tanzu.vmware.com/has-tests: "true"
      apps.tanzu.vmware.com/workload-type: worker
      carto.run/workload-name: tekton
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"tekton","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"worker"},"name":"tekton","namespace":"dev"},"spec":{"params":[{"name":"testing_pipeline_matching_labels","value":{"apps.tanzu.vmware.com/pipeline":"golang"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/tektoncd/pipeline"}}}}
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: tekton
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: worker
        carto.run/workload-name: tekton
    spec:
      containers:
      - image: gcr.io/rawlingsj/tekton-dev@sha256:35765c4fe3755512a3bf065bb0400ac6a1c3c5a1eb9881c52dcf394f44fef707
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

